# Generated by Django 3.1.7 on 2021-03-28 11:48

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20210324_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bbank',
            name='important',
        ),
        migrations.RemoveField(
            model_name='bbank',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='bbank',
            name='title',
        ),
        migrations.AddField(
            model_name='bbank',
            name='bloodgrp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='bbank',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bbank',
            name='firstname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bbank',
            name='lastname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bbank',
            name='mobile',
            field=phone_field.models.PhoneField(max_length=31, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='bbank',
            name='user_address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='bbank',
            name='user_age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
