# Generated by Django 3.1.7 on 2021-03-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20210328_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bbank',
            name='user_address',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
