# Generated by Django 3.1.7 on 2021-03-28 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20210328_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bbank',
            name='mobile',
        ),
    ]
