# Generated by Django 3.1.7 on 2021-04-19 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0005_remove_bbank_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='donarreg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('user_age', models.IntegerField(blank=True, null=True)),
                ('bloodgrp', models.CharField(blank=True, max_length=4, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('datecompleted', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_address', models.TextField(max_length=300, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
